name: test
on:
  push:

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: checkout repository
        uses: actions/checkout@v3

      - name: run go test
        run: |
          ls -la
          pwd
